<?php

return [
    'categories' => [
        [
            'id' => 1,
            'name' => 'horror',
        ],
        [
            'id' => 2,
            'name' => 'Mobile tech',
        ],
        [
            'id' => 3,
            'name' => 'Новости',
        ],
        [
            'id' => 4,
            'name' => 'fantazy',
        ],
        [
            'id' => 5,
            'name' => 'movies',
        ],
        [
            'id' => 6,
            'name' => 'nature',
        ],
        [
            'id' => 7,
            'name' => 'music',
        ],
    ],
    'statuses' => [
        [
            'id' => 1,
            'name' => 'published',
        ],
        [
            'id' => 2,
            'name' => 'unpublished',
        ],
    ],
    'authors' => [
        [
            'id' => 1,
            'name' => 'Stiven King',
        ],
        [
            'id' => 2,
            'name' => 'Semerenko Valdimir',
        ],
        [
            'id' => 3,
            'name' => 'Stiven King',
        ],
        [
            'id' => 4,
            'name' => 'George Martin',
        ],
        [
            'id' => 5,
            'name' => 'Vladymyr Gryshyn',
        ],
        [
            'id' => 6,
            'name' => 'Kotsupiy Nicholay',
        ],
        [
            'id' => 7,
            'name' => 'Michael Jackson',
        ],
    ],
    'posts' => [
        [
            'id' => 1,
            'title' => 'Christina',
            'author' => 1,
            'status' => 1,
            'category' => 1,
            'img' => 'https://s1.livelib.ru/boocover/1001388434/o/8f54/Stiven_King__Kristina.jpeg',
            'content' => 'It was love at first sight. When seventeen-year-old Arnie saw Christina, he realized: they must belong to each other. However, the others did not share his delight. Best friend, Dennis, immediately became suspicious of Christine. A friend, the first school beauty, was jealous of Arnie for Christina and was afraid of her. But soon both relatives and enemies of Arnie will understand what happens if you cross Christinas road. Because Christina is not a girl, but a death machine generated by Evil ...',
        ],
        [
            'id' => 2,
            'title' => 'About NFC',
            'author' => 2,
            'status' => 1,
            'category' => 2,
            'img' => 'https://99designs-blog.imgix.net/blog/wp-content/uploads/2018/06/NFC.jpg',
            'content' => 'The first quote you may recognise from Lindon Leader who’s famed designs include FedEx, Disney, and Hawaiian Airlines. The second quote is from Albert Einstein. I chose both these quotes to start this piece for 3 take away words I want you to remember:',
        ],
        [
            'id' => 3,
            'title' => 'Новости',
            'author' => 3,
            'status' => 2,
            'category' => 3,
            'img' => 'https://bipbap.ru/wp-content/uploads/2017/05/VOLKI-krasivye-i-ochen-umnye-zhivotnye.jpg',
            'content' =>'Равным образом рамки и место обучения кадров представляет собой интересный эксперимент проверки системы обучения кадров, соответствует насущным потребностям. Значимость этих проблем настолько очевидна, что сложившаяся структура организации в значительной степени обуславливает создание соответствующий условий активизации. Задача организации, в особенности же укрепление и развитие структуры позволяет выполнять важные задания по разработке существенных финансовых и административных услови',
        ],
        [
            'id' => 4,
            'title' => 'Song of ice and fire',
            'author' => 4,
            'status' => 1,
            'category' => 4,
            'img' => 'https://kbimages1-a.akamaihd.net/271b14a5-2d8c-4889-b7b7-72e52e644f53/353/569/90/False/a-clash-of-kings-a-song-of-ice-and-fire-book-2-1.jpg',
            'content' => 'Sed ut perspiciatis, unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam eaque ipsa, quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt, explicabo. Nemo enim ipsam voluptatem, quia voluptas sit, aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos, qui ratione voluptatem sequi nesciunt, neque porro quisquam est, qui dolorem ipsum, quia dolor sit, amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt, ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur?'
        ],
        [
            'id' => 5,
            'title' => 'Star wars:Empire strickes back',
            'author' => 5,
            'status' => 2,
            'category' => 5,
            'img' => 'https://i.etsystatic.com/14403810/r/il/047211/1197150509/il_570xN.1197150509_hg99.jpg',
            'content' => 'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.',
        ],
        [
            'id' => 6,
            'title' => 'Nature news',
            'author' => 6,
            'status' => 1,
            'category' => 6,
            'img' => 'https://www.google.com/search?q=image&client=ubuntu&hs=hY7&tbm=isch&source=iu&ictx=1&fir=I0zAF9TavGWK5M%252Cy3nWK2hdEell5M%252C_&vet=1&usg=AI4_-kRNm613xE0hfVgSaC4FgRPQ0BI8cA&sa=X&ved=2ahUKEwj5iv-QldPuAhVE2-AKHXmjArwQ9QF6BAgPEAE&biw=1853&bih=953#imgrc=I0zAF9TavGWK5M',
            'content' => 'Noise from shipping, construction, sonar and seismic surveys is "drowning out" the healthy ocean soundscape, scientists say.'
        ],
        [
            'id' => 7,
            'title' => 'Black Or White',
            'author' => 7,
            'status' => 1,
            'category' => 7,
            'img' => 'https://www.film.ru/sites/default/files/people/1463555-905629.jpg',
            'content' => 'The eighth child of the Jackson family, Jackson made his professional debut in 1964 with his elder brothers Jackie, Tito, Jermaine, and Marlon as a member of the Jackson 5. Jackson began his solo career in 1971 while at Motown Records, and rose to solo stardom with his fifth studio album Off the Wall (1979) during the peak of the disco era',
        ],
    ]
];